//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.4.4
//     from Assets/Input/Player Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""Player Controls"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""2b486a4d-9626-41f3-bba7-3d365a1cea27"",
            ""actions"": [
                {
                    ""name"": ""Movement"",
                    ""type"": ""PassThrough"",
                    ""id"": ""91d3e57c-c173-4e25-876f-285078e8f894"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar 1"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f19b922a-37e9-4c04-aea5-0a919fd664c7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar 2"",
                    ""type"": ""PassThrough"",
                    ""id"": ""03cae562-e0bc-45e6-be1e-84a6b6b2f605"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar 3"",
                    ""type"": ""PassThrough"",
                    ""id"": ""10193bc3-2f1d-4104-86e5-d2e9b3f67833"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar 4"",
                    ""type"": ""PassThrough"",
                    ""id"": ""48460065-6a8e-4000-89c1-1cb932f712e8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar 5"",
                    ""type"": ""PassThrough"",
                    ""id"": ""229bcc19-40a2-4950-8cd4-0190c7b2a794"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar 6"",
                    ""type"": ""PassThrough"",
                    ""id"": ""89887f99-2e17-4e7b-be08-a86541237961"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar 7"",
                    ""type"": ""PassThrough"",
                    ""id"": ""d630c936-39a9-4929-8f0d-c125497ac6a0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar 8"",
                    ""type"": ""PassThrough"",
                    ""id"": ""3b4d8111-c9be-4140-86d5-e9acec4a0ea3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar 9"",
                    ""type"": ""PassThrough"",
                    ""id"": ""93e3d70d-7094-43c3-8cee-56703931dd84"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Hotbar 10"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f1e1463e-18a8-496a-9a00-42f8e5c05296"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mouse Wheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""cd0d7900-5c54-4233-a21c-cee6f53c182f"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Use Item"",
                    ""type"": ""Button"",
                    ""id"": ""c4be197b-2900-43ac-8e07-3af63bdee331"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""8327d726-a252-4e1b-94f5-e5eeb984acfa"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""058846e7-b5d8-4ddb-afc0-ad85f1214199"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""62924777-34f8-4149-a083-f5da767eb4ac"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""5cd9db0d-d11e-4206-8db4-bb8cfc4a230a"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""1b0f1f34-08ba-4eab-901b-532aafc06dfc"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Movement"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""eeb9354f-fe96-4971-a3cb-bfb2837e976c"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar 1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0e644997-c142-4938-8aa0-2a65d3207f23"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar 2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aecf0951-3688-4fe1-ad21-53cdc0112b58"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar 3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""32e10bb5-eded-48cd-83cc-942c1dccb1c4"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar 4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7922da5-9d30-4947-ac0f-572731c68463"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar 5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4188fb19-bf45-4ac5-9ba9-beaeb42aec3b"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar 6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10cd1644-8840-45b0-b59b-99f9c8e6cd22"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar 7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8147be9a-2a6b-45fe-8a1f-d1bfb77baffa"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar 8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""143c70bd-365f-4b52-8705-01f876f0ab08"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar 9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b2224a70-ac2f-45a8-85ad-22065a575e91"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Hotbar 10"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b5142c2-0fca-4d0f-9742-2715b88cea74"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mouse Wheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8028ded4-6181-4d77-a86d-4000c379b6b6"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Use Item"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Movement = m_Player.FindAction("Movement", throwIfNotFound: true);
        m_Player_Hotbar1 = m_Player.FindAction("Hotbar 1", throwIfNotFound: true);
        m_Player_Hotbar2 = m_Player.FindAction("Hotbar 2", throwIfNotFound: true);
        m_Player_Hotbar3 = m_Player.FindAction("Hotbar 3", throwIfNotFound: true);
        m_Player_Hotbar4 = m_Player.FindAction("Hotbar 4", throwIfNotFound: true);
        m_Player_Hotbar5 = m_Player.FindAction("Hotbar 5", throwIfNotFound: true);
        m_Player_Hotbar6 = m_Player.FindAction("Hotbar 6", throwIfNotFound: true);
        m_Player_Hotbar7 = m_Player.FindAction("Hotbar 7", throwIfNotFound: true);
        m_Player_Hotbar8 = m_Player.FindAction("Hotbar 8", throwIfNotFound: true);
        m_Player_Hotbar9 = m_Player.FindAction("Hotbar 9", throwIfNotFound: true);
        m_Player_Hotbar10 = m_Player.FindAction("Hotbar 10", throwIfNotFound: true);
        m_Player_MouseWheel = m_Player.FindAction("Mouse Wheel", throwIfNotFound: true);
        m_Player_UseItem = m_Player.FindAction("Use Item", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Movement;
    private readonly InputAction m_Player_Hotbar1;
    private readonly InputAction m_Player_Hotbar2;
    private readonly InputAction m_Player_Hotbar3;
    private readonly InputAction m_Player_Hotbar4;
    private readonly InputAction m_Player_Hotbar5;
    private readonly InputAction m_Player_Hotbar6;
    private readonly InputAction m_Player_Hotbar7;
    private readonly InputAction m_Player_Hotbar8;
    private readonly InputAction m_Player_Hotbar9;
    private readonly InputAction m_Player_Hotbar10;
    private readonly InputAction m_Player_MouseWheel;
    private readonly InputAction m_Player_UseItem;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @Movement => m_Wrapper.m_Player_Movement;
        public InputAction @Hotbar1 => m_Wrapper.m_Player_Hotbar1;
        public InputAction @Hotbar2 => m_Wrapper.m_Player_Hotbar2;
        public InputAction @Hotbar3 => m_Wrapper.m_Player_Hotbar3;
        public InputAction @Hotbar4 => m_Wrapper.m_Player_Hotbar4;
        public InputAction @Hotbar5 => m_Wrapper.m_Player_Hotbar5;
        public InputAction @Hotbar6 => m_Wrapper.m_Player_Hotbar6;
        public InputAction @Hotbar7 => m_Wrapper.m_Player_Hotbar7;
        public InputAction @Hotbar8 => m_Wrapper.m_Player_Hotbar8;
        public InputAction @Hotbar9 => m_Wrapper.m_Player_Hotbar9;
        public InputAction @Hotbar10 => m_Wrapper.m_Player_Hotbar10;
        public InputAction @MouseWheel => m_Wrapper.m_Player_MouseWheel;
        public InputAction @UseItem => m_Wrapper.m_Player_UseItem;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Movement.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Movement.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMovement;
                @Hotbar1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar1;
                @Hotbar1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar1;
                @Hotbar1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar1;
                @Hotbar2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar2;
                @Hotbar2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar2;
                @Hotbar2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar2;
                @Hotbar3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar3;
                @Hotbar3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar3;
                @Hotbar3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar3;
                @Hotbar4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar4;
                @Hotbar4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar4;
                @Hotbar4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar4;
                @Hotbar5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar5;
                @Hotbar5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar5;
                @Hotbar5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar5;
                @Hotbar6.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar6;
                @Hotbar6.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar6;
                @Hotbar6.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar6;
                @Hotbar7.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar7;
                @Hotbar7.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar7;
                @Hotbar7.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar7;
                @Hotbar8.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar8;
                @Hotbar8.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar8;
                @Hotbar8.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar8;
                @Hotbar9.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar9;
                @Hotbar9.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar9;
                @Hotbar9.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar9;
                @Hotbar10.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar10;
                @Hotbar10.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar10;
                @Hotbar10.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar10;
                @MouseWheel.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseWheel;
                @MouseWheel.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseWheel;
                @MouseWheel.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMouseWheel;
                @UseItem.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseItem;
                @UseItem.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseItem;
                @UseItem.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseItem;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Movement.started += instance.OnMovement;
                @Movement.performed += instance.OnMovement;
                @Movement.canceled += instance.OnMovement;
                @Hotbar1.started += instance.OnHotbar1;
                @Hotbar1.performed += instance.OnHotbar1;
                @Hotbar1.canceled += instance.OnHotbar1;
                @Hotbar2.started += instance.OnHotbar2;
                @Hotbar2.performed += instance.OnHotbar2;
                @Hotbar2.canceled += instance.OnHotbar2;
                @Hotbar3.started += instance.OnHotbar3;
                @Hotbar3.performed += instance.OnHotbar3;
                @Hotbar3.canceled += instance.OnHotbar3;
                @Hotbar4.started += instance.OnHotbar4;
                @Hotbar4.performed += instance.OnHotbar4;
                @Hotbar4.canceled += instance.OnHotbar4;
                @Hotbar5.started += instance.OnHotbar5;
                @Hotbar5.performed += instance.OnHotbar5;
                @Hotbar5.canceled += instance.OnHotbar5;
                @Hotbar6.started += instance.OnHotbar6;
                @Hotbar6.performed += instance.OnHotbar6;
                @Hotbar6.canceled += instance.OnHotbar6;
                @Hotbar7.started += instance.OnHotbar7;
                @Hotbar7.performed += instance.OnHotbar7;
                @Hotbar7.canceled += instance.OnHotbar7;
                @Hotbar8.started += instance.OnHotbar8;
                @Hotbar8.performed += instance.OnHotbar8;
                @Hotbar8.canceled += instance.OnHotbar8;
                @Hotbar9.started += instance.OnHotbar9;
                @Hotbar9.performed += instance.OnHotbar9;
                @Hotbar9.canceled += instance.OnHotbar9;
                @Hotbar10.started += instance.OnHotbar10;
                @Hotbar10.performed += instance.OnHotbar10;
                @Hotbar10.canceled += instance.OnHotbar10;
                @MouseWheel.started += instance.OnMouseWheel;
                @MouseWheel.performed += instance.OnMouseWheel;
                @MouseWheel.canceled += instance.OnMouseWheel;
                @UseItem.started += instance.OnUseItem;
                @UseItem.performed += instance.OnUseItem;
                @UseItem.canceled += instance.OnUseItem;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnMovement(InputAction.CallbackContext context);
        void OnHotbar1(InputAction.CallbackContext context);
        void OnHotbar2(InputAction.CallbackContext context);
        void OnHotbar3(InputAction.CallbackContext context);
        void OnHotbar4(InputAction.CallbackContext context);
        void OnHotbar5(InputAction.CallbackContext context);
        void OnHotbar6(InputAction.CallbackContext context);
        void OnHotbar7(InputAction.CallbackContext context);
        void OnHotbar8(InputAction.CallbackContext context);
        void OnHotbar9(InputAction.CallbackContext context);
        void OnHotbar10(InputAction.CallbackContext context);
        void OnMouseWheel(InputAction.CallbackContext context);
        void OnUseItem(InputAction.CallbackContext context);
    }
}
